### ISSUE TITLE
How to Load image from device

### ISSUE THREAD

**Issue by mushroomgenie** [gre/gl-react-image#33]
`<GLImage source={{uri:"https://i.imgur.com/uTP9Xfr.jpg"}} resizeMode="contain"/>` this works perfectly fine.
But
`<GLImage source={{uri:"file://..."}} resizeMode="contain"/>` this renders nothing. I have tried using `resolveAssetSource` but no luck there as well. 
@gre Help would be really appreciated. Thank You

**Comment by mistikk** [comment]
same issue

**Comment by bwoodlt** [comment]
Having the same issue...

**Comment by mushroomgenie** [comment]
Any update on this ? @gre

**Comment by emrahtoy** [comment]
I have been dealing the same problem. Usual \<Image\> works with the original uri but \<GLImage\> doesn't work ( i picked the uri by using expo mediaLibrary ).

It seems like encoding problem but may also related with the async process problem. 

I have solved my problem with using FileSystem of expo instead of relying on GLImage uri process.

Here is the code;

`
            FileSystem.getInfoAsync(image!).then(info => {
                console.log(info)
                this.setState({ image: info.uri});
            }).catch(e => console.log(e));
`

Here, image variable is the current uri of the image ( taken by mediaLibrary ) . After all FileSystem gathers the info, i set the image variable with the info.uri ( which has slightly different encoding then original uri ) and i used it with `<GLImage  source={{uri: this.state.image}}></GLImage>` 

Note : @gre  this might be happening due to that expo depreciated expo-assets

**Comment by gre** [comment]
Can you confirm this is now fixed in this upcoming version? Thanks

```
 - gl-react-dom => 5.2.2-next.6+d39872d
 - gl-react-expo => 5.2.2-next.6+d39872d
 - gl-react-headless => 5.2.2-next.6+d39872d
 - gl-react-native => 5.2.2-next.6+d39872d
 - gl-react => 5.2.2-next.6+d39872d
```
