### ISSUE TITLE
Using gifs

### ISSUE THREAD

**Issue by uRTLy** [gre/gl-react-image#8]
(react native)
Hello, guys do you have any ideas how to animate gifs  with this component ? Is it even possible ?

**Comment by gre** [comment]
that's probably more a question for the underlying implementation (gl-react-dom / gl-react-native)

I'm pretty sure it works in the Web implementation, but you will have to re trigger a draw to see the gif image being updated.
For React Native, I don't really know if it works. the v2 implementation might or might not support that, not tested (but you probably have tested and it doesn't work? have you try to trigger a render update each N ms ?) . for the future v3 implementation, I will have to ask that to exponent team since we will rely on forking Exponent GLView implementation.
